export const skillList = [
  { key: "acrobatics", label: "Acrobatics", ability: "Dexterity" },
  { key: "animal_handling", label: "Animal Handling", ability: "Wisdom" },
  { key: "arcana", label: "Arcana", ability: "Intelligence" },
  { key: "athletics", label: "Athletics", ability: "Strength" },
  { key: "deception", label: "Deception", ability: "Charisma" },
  { key: "history", label: "History", ability: "Intelligence" },
  { key: "insight", label: "Insight", ability: "Wisdom" },
  { key: "intimidation", label: "Intimidation", ability: "Charisma" },
  { key: "investigation", label: "Investigation", ability: "Intelligence" },
  { key: "medicine", label: "Medicine", ability: "Wisdom" },
  { key: "nature", label: "Nature", ability: "Intelligence" },
  { key: "perception", label: "Perception", ability: "Wisdom" },
  { key: "performance", label: "Performance", ability: "Charisma" },
  { key: "persuasion", label: "Persuasion", ability: "Charisma" },
  { key: "religion", label: "Religion", ability: "Intelligence" },
  { key: "sleight_of_hand", label: "Sleight of Hand", ability: "Dexterity" },
  { key: "stealth", label: "Stealth", ability: "Dexterity" },
  { key: "survival", label: "Survival", ability: "Wisdom" },
];
